# Generated by Django 2.2.3 on 2020-03-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('flat_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('rent', models.IntegerField()),
            ],
        ),
    ]
