# Generated by Django 2.2.3 on 2020-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='rent',
            field=models.IntegerField(default=1),
        ),
    ]
