# Generated by Django 2.2.3 on 2020-03-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatshare', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.IntegerField(default=888, unique=True),
        ),
    ]
