# Generated by Django 2.2.3 on 2020-03-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatshare', '0004_auto_20200313_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('house_no', models.CharField(max_length=50)),
                ('postCode', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=128)),
            ],
        ),
    ]
