# Generated by Django 2.2.3 on 2020-03-13 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flatshare', '0005_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='flat',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='flatshare.Flat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flat',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
