# Generated by Django 2.2.3 on 2020-03-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatshare', '0006_auto_20200313_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='flat',
        ),
    ]
