# Generated by Django 2.2.3 on 2020-03-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatshare', '0007_remove_address_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='flatshare.Address'),
            preserve_default=False,
        ),
    ]
