# Generated by Django 2.2.3 on 2020-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatshare', '0009_auto_20200313_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_addFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password_addFlat', models.CharField(max_length=128)),
                ('email_addflat', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_findFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password_findflat', models.CharField(max_length=128)),
                ('email_findflat', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flat',
            name='city',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='postCode',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='street',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='user',
        ),
    ]
