# Generated by Django 2.2.3 on 2020-03-19 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatshare', '0010_auto_20200319_1015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profile_addFlat',
        ),
        migrations.AlterField(
            model_name='profile_addflat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatshare.User_addFlat'),
        ),
    ]
