# Generated by Django 2.2.3 on 2020-03-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatshare', '0011_auto_20200319_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='flat_images')),
                ('iamge_flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatshare.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('house_no', models.CharField(max_length=50)),
                ('postCode', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=128)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flatshare.Flat')),
            ],
        ),
    ]
